apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-cloud-app
  template:
    metadata:
      labels:
        app: k8s-cloud-app
    spec:
      containers:
      - name: k8s-cloud-app
        image: your-dockerhub-username/k8s-cloud-app:latest
        ports:
        - containerPort: 80
